### ISSUE TITLE
todo edit <invalid id> - error not handled

### ISSUE THREAD

**Issue by RJ722** [pimutils/todoman#223]
If this is run:    ```todo edit 12``` (Assume 12 is not a valid id), then a python exception occurs:
```
Traceback (most recent call last):
  File "/usr/local/bin/todo", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/todoman/cli.py", line 62, in command_wrap
    return command(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/todoman/cli.py", line 170, in edit
    todo = database.todo(id)
  File "/usr/local/lib/python3.5/dist-packages/todoman/model.py", line 811, in todo
    return self.cache.todo(id)
  File "/usr/local/lib/python3.5/dist-packages/todoman/model.py", line 699, in todo
    raise NoSuchTodo()
todoman.model.NoSuchTodo
```
Is this the required behaviour? 
We can perhaps handle the exception and display a descent error message.

**Comment by hobarrera** [comment]
Definitely a bug.
#222 slightly changes how we address these cases, but I think it's just a matter of adding the `catch_errors` decorator to `edit`.

**Comment by hobarrera** [comment]
#222 fixed this, but I'll leave this issue open as a reminder to add tests to avoid regressions.

**Comment by AnubhaAgrawal** [comment]
In this issue, I don't get python exception when I input invalid id.
```(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo 
16  [ ]    2017-04-01 08:42:18 PM  Hello everyone @Anu
15  [ ]    2017-04-01 08:28:03 PM  Hello @Anu
14  [ ]    2017-04-01 08:17:09 PM  Hello Everyone1111 @anu1
12  [ ]    2017-03-02 03:09:45 PM  Hello everyone @anu1
 4  [ ]    2017-03-02 02:02:38 PM  Hello todoman  @Anu
 9  [ ]    2017-03-02 07:31:45 AM  test3 @anu1
10  [ ]    2017-03-02 07:30:38 AM  test3 @anu1
 6  [ ]    2017-03-02 07:30:20 AM  test3 @anu1
 1  [ ]    2017-03-02 07:30:11 AM  test3 @anu1
13  [ ]    2017-03-02 07:28:22 AM  test3 @anu1
 3  [ ]    2017-03-02 07:25:54 AM  test3 @anu1
11  [ ]    2017-03-02 07:25:49 AM  test2 @anu1
 5  [ ]    2017-03-02 07:24:47 AM  test @anu1
 2  [ ]    2017-02-28 04:47:47 PM  event @default
(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo edit 3
3  [ ]    2017-03-02 07:25:54 AM  test3 @anu1
(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo edit 7
7  [X]    2017-03-02 07:25:29 AM  test2 @anu1 (100%)

Description  Editied
Location     Sadabad
(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo edit 22
No todo with id 22.
(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo edit 50
No todo with id 50.
```
I do something wrong??

**Comment by hobarrera** [comment]
I clarified this above: this was fixed as a side effect of another change, but I just left this open as a reminder to add a test. I'm adding one right now though. ^_^
