### ISSUE TITLE
todo crashes with IndexError: No item with that key

### ISSUE THREAD

**Issue by jdkbx** [pimutils/todoman#224]
after simply running todo (3.0.0)

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/todo", line 11, in <module>
    load_entry_point('todoman==3.0.0', 'console_scripts', 'todo')()
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/click_log/core.py", line 94, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 125, in wrapper
    return handle_error(e)
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 131, in handle_error
    raise e
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 123, in wrapper
    return f(*a, **kw)
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 228, in cli
    click_ctx.invoke(cli.commands["list"])
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 125, in wrapper
    return handle_error(e)
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 131, in handle_error
    raise e
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 123, in wrapper
    return f(*a, **kw)
  File "/usr/lib64/python3.4/site-packages/todoman/cli.py", line 447, in list
    click.echo(ctx.formatter.compact_multiple(todos))
  File "/usr/lib64/python3.4/site-packages/todoman/formatters.py", line 37, in compact_multiple
    for todo in todos:
  File "/usr/lib64/python3.4/site-packages/todoman/model.py", line 665, in todos
    todo = self._todo_from_db(row)
  File "/usr/lib64/python3.4/site-packages/todoman/model.py", line 686, in _todo_from_db
    todo.start = self._dt_from_db(row['start'])
IndexError: No item with that key
```

**Comment by hobarrera** [comment]
Can you try running `~/.cache/todoman/cache.sqlite3`?

I think this is something that was fixed on v3.0.1 (release like, 5 minutes after v3.0.0 :P )

**Comment by jdkbx** [comment]
You are right. 3.0.1 fixes it. Did not see it, as 3.0.0 is still listed prominently as latest release and my release informer (sibbel) did not pick it up either. Thanks.

**Comment by hobarrera** [comment]
Looks like a bug on their side. Also, the publication dates for a lot of them are wrong, and several are missing. ([All versions are here](https://github.com/pimutils/todoman/tags)). You might want to report it.

Our of mere curiosity; what distribution are you using?

**Comment by jdkbx** [comment]
Yeah, I have seen this happening on github before, when you release
multiple versions in short sequence. I probably just overlooked it.

Gentoo
