### ISSUE TITLE
setup.py apparently does not respect sandbox

### ISSUE THREAD

**Issue by drkhsh** [pimutils/todoman#262]
i tried to package todoman for gentoo, but apparently setup.py does not respect sandboxes. i am not a python guru myself, so maybe you can help me with it.

log:
```
>>> Checking todoman-3.2.0.tar.gz's mtime...
>>> WORKDIR is up-to-date, keeping...
Appending /home/drkhsh/git/overlay to PORTDIR_OVERLAY...
>>> It appears that 'pretend' has already executed for 'todoman-3.2.0'; skipping.
>>> Remove '/var/tmp/portage/app-misc/todoman-3.2.0/.pretended' to force pretend.
>>> It appears that 'setup' has already executed for 'todoman-3.2.0'; skipping.
>>> Remove '/var/tmp/portage/app-misc/todoman-3.2.0/.setuped' to force setup.
>>> It appears that 'unpack' has already executed for 'todoman-3.2.0'; skipping.
>>> Remove '/var/tmp/portage/app-misc/todoman-3.2.0/.unpacked' to force unpack.
>>> It appears that 'prepare' has already executed for 'todoman-3.2.0'; skipping.
>>> Remove '/var/tmp/portage/app-misc/todoman-3.2.0/.prepared' to force prepare.
>>> It appears that 'configure' has already executed for 'todoman-3.2.0'; skipping.
>>> Remove '/var/tmp/portage/app-misc/todoman-3.2.0/.configured' to force configure.
>>> Compiling source in /var/tmp/portage/app-misc/todoman-3.2.0/work/todoman-3.2.0 ...
 python3_4: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python3.4 setup.py build
Traceback (most recent call last):
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.4/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.4/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib64/python3.4/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.4/site-packages/setuptools/command/build_py.py", line 49, in run
    self.build_modules()
  File "/usr/lib64/python3.4/distutils/command/build_py.py", line 352, in build_modules
    self.build_module(module, module_file, package)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/build_py.py", line 75, in build_module
    package)
  File "/usr/lib64/python3.4/distutils/command/build_py.py", line 343, in build_module
    return self.copy_file(module_file, outfile, preserve_mode=0)
  File "/usr/lib64/python3.4/distutils/cmd.py", line 348, in copy_file
    dry_run=self.dry_run)
  File "/usr/lib64/python3.4/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/lib64/python3.4/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 420, in _open
    self._violation("open", path, mode, *args, **kw)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 409, in _violation
    raise SandboxViolation(operation, args, kw)
setuptools.sandbox.SandboxViolation: SandboxViolation: open('/var/tmp/portage/app-misc/todoman-3.2.0/work/todoman-3.2.0-python3_4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/tmp/portage/app-misc/todoman-3.2.0/temp/easy_install-ouhfe0p4/pytest-runner-2.11.1/setup.py", line 49, in <module>
  File "/usr/lib64/python3.4/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: SandboxViolation: open('/var/tmp/portage/app-misc/todoman-3.2.0/work/todoman-3.2.0-python3_4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib64/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib64/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/tmp/portage/app-misc/todoman-3.2.0/temp/easy_install-ouhfe0p4/pytest-runner-2.11.1/setup.py", line 49, in <module>
  File "/usr/lib64/python3.4/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: SandboxViolation: open('/var/tmp/portage/app-misc/todoman-3.2.0/work/todoman-3.2.0-python3_4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    'Topic :: Utilities',
  File "/usr/lib64/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib64/python3.4/site-packages/setuptools/dist.py", line 317, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib64/python3.4/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/usr/lib64/python3.4/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: open('/var/tmp/portage/app-misc/todoman-3.2.0/work/todoman-3.2.0-python3_4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
ERROR: app-misc/todoman-3.2.0::drkhsh-overlay failed (compile phase):
   (no error message)
 
 Call stack:
     ebuild.sh, line  115:  Called src_compile
   environment, line 2657:  Called distutils-r1_src_compile
   environment, line  806:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
    environment, line  321:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
   environment, line 2201:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
   environment, line 1507:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
   environment, line 1505:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
   environment, line  536:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
   environment, line  797:  Called distutils-r1_python_compile
   environment, line  672:  Called esetup.py 'build'
   environment, line 1052:  Called die
 The specific snippet of code:
       "${@}" || die "${die_args[@]}";
 
 If you need support, post the output of `emerge --info '=app-misc/todoman-3.2.0::drkhsh-overlay'`,
  the complete build log and the output of `emerge -pqv '=app-misc/todoman-3.2.0::drkhsh-overlay'`.
 The complete build log is located at '/var/tmp/portage/app-misc/todoman-3.2.0/temp/build.log'.
 The ebuild environment file is located at '/var/tmp/portage/app-misc/todoman-3.2.0/temp/environment'.
 Working directory: '/var/tmp/portage/app-misc/todoman-3.2.0/work/todoman-3.2.0'
 S: '/var/tmp/portage/app-misc/todoman-3.2.0/work/todoman-3.2.0'
```

**Comment by hobarrera** [comment]
Are you talking about [this sandbox](https://pypi.python.org/pypi/sandbox). If so, that's not really something we support, but we're not doing anything funky either, so if something fails, it's probably on their end.

TBH, our `setup.py` file is extremely basic and standard; there's nothing odd being done. It really sounds like an issue with the sandbox you're using itself. Does `setup.py` for other stuff run fine? (eg: requests?).

**Comment by drkhsh** [comment]
Hm ok, thank you for your reply. Other setup.py run normally :cry: I will have a look again …

**Comment by hobarrera** [comment]
Any update?

**Comment by drkhsh** [comment]
I had a look at other python ebuilds and they do the same thing from Gentoo's side. Something has to be different...

**Comment by hobarrera** [comment]
The [`setup.py`](https://github.com/pimutils/todoman/blob/master/setup.py) is extremely basic and has nothing out of the ordinary.

Did you make sure all the dependencies and build dependencies (`setup_requires`) are installed properly? IIRC, if they're not, `setuptools` will download it into the directory containing `setup.py` (which might be outside of your working/sandbox area).

Otherwise, can you determine _which_ file is being written to?

**Comment by drkhsh** [comment]
I will have a look again, thanks

**Comment by drkhsh** [comment]
Seems to be solved in latest version. Sorry for the noise.
