### ISSUE TITLE
AttributeError: module 'click_log' has no attribute 'init'

### ISSUE THREAD

**Issue by ellioseven** [pimutils/todoman#266]
Getting the following error when running:

```
pip3 install todoman && todo
```

```
Traceback (most recent call last):
  File "/usr/bin/todo", line 7, in <module>
    from todoman.cli import cli
  File "/usr/lib/python3.6/site-packages/todoman/cli.py", line 195, in <module>
    @click_log.init('todoman')
AttributeError: module 'click_log' has no attribute 'init'
```

Here is the entire log:

```
$ python --version
Python 3.6.1

$ pip3 --version
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)

$ pip3 install todoman
Collecting todoman
  Downloading todoman-3.2.0-py3-none-any.whl
Collecting configobj (from todoman)
  Downloading configobj-5.0.6.tar.gz
Collecting tabulate (from todoman)
  Downloading tabulate-0.7.7-py2.py3-none-any.whl
Collecting python-dateutil (from todoman)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
Collecting urwid (from todoman)
  Downloading urwid-1.3.1.tar.gz (588kB)
Collecting pyxdg (from todoman)
  Downloading pyxdg-0.25.tar.gz (48kB)
Collecting parsedatetime (from todoman)
  Downloading parsedatetime-2.4.tar.gz (58kB)
Collecting click-log>=0.1.3 (from todoman)
  Downloading click_log-0.2.0-py2.py3-none-any.whl
Collecting atomicwrites (from todoman)
  Downloading atomicwrites-1.1.5-py2.py3-none-any.whl
Collecting humanize (from todoman)
  Downloading humanize-0.5.1.tar.gz
Collecting click>=6.0 (from todoman)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting icalendar (from todoman)
  Downloading icalendar-3.11.7-py2.py3-none-any.whl (77kB)
Collecting six (from configobj->todoman)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting future (from parsedatetime->todoman)
  Downloading future-0.16.0.tar.gz (824kB)
Collecting pytz (from icalendar->todoman)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
Installing collected packages: six, configobj, tabulate, python-dateutil, urwid, pyxdg, future, parsedatetime, click, click-log, atomicwrites, humanize, pytz, icalendar, todoman
  Running setup.py install for configobj: started
    Running setup.py install for configobj: finished with status 'done'
  Running setup.py install for urwid: started
    Running setup.py install for urwid: finished with status 'done'
  Running setup.py install for pyxdg: started
    Running setup.py install for pyxdg: finished with status 'done'
  Running setup.py install for future: started
    Running setup.py install for future: finished with status 'done'
  Running setup.py install for parsedatetime: started
    Running setup.py install for parsedatetime: finished with status 'done'
  Running setup.py install for humanize: started
    Running setup.py install for humanize: finished with status 'done'
Successfully installed atomicwrites-1.1.5 click-6.7 click-log-0.2.0 configobj-5.0.6 future-0.16.0 humanize-0.5.1 icalendar-3.11.7 parsedatetime-2.4 python-dateutil-2.6.1 pytz-2017.2 pyxdg-0.25 six-1.10.0 tabulate-0.7.7 todoman-3.2.0 urwid-1.3.1

$ todo
Traceback (most recent call last):
  File "/usr/bin/todo", line 7, in <module>
    from todoman.cli import cli
  File "/usr/lib/python3.6/site-packages/todoman/cli.py", line 195, in <module>
    @click_log.init('todoman')
AttributeError: module 'click_log' has no attribute 'init'
```

However, this doesn't seem to be an issue on the current development branch.

**Comment by hobarrera** [comment]
Odd. 3.2.1 was released a few days ago, and while pypi sometimes takes a few minutes/hours, or should be visible already.

Let me follow up on pypi's side and get back to you.

--
Hugo Osvaldo Barrera

**Comment by hobarrera** [comment]
I've re-pushed [v3.2.1](https://pypi.python.org/pypi/todoman/3.2.1). I've no idea why the previous PyPI push never appeared.
