### ISSUE TITLE
"todo shell" and "todo repl" crash when executed

### ISSUE THREAD

**Issue by kamikazejoe** [pimutils/todoman#289]
Just immediately bombs out on me.
Running Arch Linux on two different systems.
Tried both the todoman and todoman-git repos in Arch's AUR.

Get the following:
```
Traceback (most recent call last):
  File "/usr/bin/todo", line 5, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click_repl/__init__.py", line 180, in repl
    command = get_command()
  File "/usr/lib/python3.6/site-packages/click_repl/__init__.py", line 174, in get_command
    return prompt(**bootstrap_prompt(prompt_kwargs, group))
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/shortcuts.py", line 541, in prompt
    application = create_prompt_application(message, **kwargs)
TypeError: create_prompt_application() got an unexpected keyword argument 'complete'
```

**Comment by WhyNotHugo** [comment]
Thanks for reporting this. Exact same issue here. I'm guessing it's some sort of API change between libs, but I'll have to look into this further.

**Comment by untitaker** [comment]
I can't reproduce this. Could anyone dump `pip freeze`?

**Comment by WhyNotHugo** [comment]
```
acme==0.19.0
alabaster==0.7.10
appdirs==1.4.3
argh==0.26.2
asn1crypto==0.23.0
atomicwrites==1.1.5
attrs==17.2.0
Automat==0.6.0
Babel==2.5.1
babelfish==0.5.5
backports.csv==1.0.5
basiciw==0.2.2
beautifulsoup4==4.6.0
blinker==1.4
brotlipy==0.7.0
cached-property==1.3.1
caffeine-ng==3.4.0
certbot==0.19.0
cffi==1.11.2
chardet==3.0.4
cli-helpers==0.2.3
click==6.7
click-log==0.2.1
click-repl==0.1.2
click-threading==0.4.4
colour==0.1.2
ConfigArgParse==0.12.0
configobj==5.0.6
constantly==15.1.0
construct==2.8.16
coverage==4.4.1
cryptography==2.1.1
cssutils==1.0.2
decorator==4.1.2
docker==2.5.1
docker-compose==1.16.1
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
dogpile.cache==0.6.4
EditorConfig==0.12.1
enzyme==0.4.1
ewmh==0.1.6
flake8==3.5.0
flake8-bugbear==17.4.0
flake8-import-order==0.11
freezegun==0.3.9
future==0.16.0
greenlet==0.4.12
guessit==2.1.4
h2==3.0.1
hpack==3.0.0
html2text==2017.10.4
httpie==0.9.9
humanize==0.5.1
hyperframe==5.1.0
hyperlink==17.3.1
hypothesis==3.33.0
i3pystatus==3.35
icalendar==3.11.7
idna==2.6
imagesize==0.7.1
incremental==17.5.0
ipdb==0.10.3
ipykernel==4.5.2
ipython==6.2.1
ipython-genutils==0.1.0
ipywidgets==6.0.0
isc==2.0
Jinja2==2.9.6
jsbeautifier==1.7.4
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
kaitaistruct==0.7
keyring==10.4.0
khal==0.9.8
Markdown==2.6.9
MarkupSafe==1.0
mccabe==0.6.1
mistune==0.7.4
mitmproxy==2.0.2
mock==2.0.0
msgpack-python==0.4.8
namcap==3.2.7
nbformat==4.4.0
neovim==0.1.13
netifaces==0.10.6
notebook==5.0.0
notmuch==0.25.1
oauthlib==2.0.6
onetimepass==1.0.1
packaging==16.8
parsedatetime==2.4
passlib==1.7.1
pathtools==0.1.2
pbr==3.1.1
pew==1.1.0
pexpect==4.2.1
pgcli==1.7.0
pgspecial==1.8.0
pickleshare==0.7.4
pipenv==8.2.6
pkginfo==1.4.1
pluggy==0.5.2
ply==3.10
prompt-toolkit==1.0.15
psycopg2==2.7.3.1
ptyprocess==0.5.2
py==1.4.34
pyalpm==0.8
pyasn1==0.3.6
PyAudio==0.2.11
pycairo==1.13.3
pycodestyle==2.3.1
pycparser==2.18
pyelftools==0.24
pyflakes==1.6.0
Pygments==2.2.0
pyOpenSSL==17.3.0
pyparsing==2.2.0
pyperclip==1.5.27
pyRFC3339==1.0
pysrt==1.1.1
pytest==3.2.3
pytest-localserver==0.3.7
pytest-subtesthack==0.1.1
python-dateutil==2.6.1
python-libtorrent==1.1.5
python-xlib==0.20
pythonz-bd==1.10.2
pytz==2017.2
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.2
rarfile==3.0
rebulk==0.9.0
regex==2017.9.23
requests==2.18.4
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
resumable-urlretrieve==0.1.5
ruamel.yaml==0.15.34
SecretStorage==2.3.1
Send2Trash==1.4.1
setproctitle==1.1.10
setuptools-scm==1.15.6
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
sortedcontainers==1.5.7
Sphinx==1.6.4
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1.dev20170522
SQLAlchemy==1.1.14
sqlparse==0.2.4
stevedore==1.27.1
subliminal==2.0.5
tabulate==0.7.7
team==1.0
terminado==0.6
terminaltables==3.1.0
texttable==1.1.0
todoman==3.2.4
tornado==4.5.2
totp==1.1.0
tox==2.9.1
traitlets==4.3.2
trash-cli==0.17.1.14
Twisted==17.9.0
txdbus==1.0.14
tzlocal==1.4
urllib3==1.22
urwid==1.3.1
vdirsyncer==0.16.3
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.8.2
watchdog==0.8.3
wcwidth==0.1.7
websocket-client==0.44.0
Werkzeug==0.12.2.dev0
Whoosh==2.7.4
widgetsnbextension==2.0.0
yapf==0.19.0
youtube-dl==2017.10.20
zope.component==4.4.1
zope.event==4.3.0
zope.interface==4.4.3
```

I can't reproduce this on a virtualenv though :|

**Comment by untitaker** [comment]
There is no package called isc, so I don't think I can repr this either?

**Comment by kamikazejoe** [comment]
So this might be working now on my ArchLinux system.  I noticed click-repl was updated, so I re-installed todoman from the AUR for grins.  Now I get a ">" prompt, and suggestions when I press TAB.  Otherwise it seems to work the same as when I run it from the Bash prompt.  Is this the expected behavior?

**Comment by untitaker** [comment]
Yes exactly

**Comment by WhyNotHugo** [comment]
Yup, seems to be working now here too.
