### ISSUE TITLE
TypeError: cli() got an unexpected keyword argument 'colour'

### ISSUE THREAD

**Issue by fauust** [pimutils/todoman#325]
Hi,
today I have this error when using todo cli.
```
Traceback (most recent call last):
  File "/usr/local/bin/todo", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
TypeError: cli() got an unexpected keyword argument 'colour'
```
```
$ pip3 search todoman
todoman (3.4.0)  - A simple CalDav-based todo manager.
  INSTALLED: 3.4.0 (latest)
```
I have removed cache and also tried with empty config file...

**Comment by WhyNotHugo** [comment]
This is because click-7.0 slightly changed their API.
Latest master is compatible with it, but I've yet to release a new version.

**Comment by WhyNotHugo** [comment]
v3.4.1 is out and fixes this.

**Comment by fauust** [comment]
wow, that was fast!
Confirmed, it's working again.
Thank you!
