### ISSUE TITLE
todo broken with click >= 7.0

### ISSUE THREAD

**Issue by dvzrv** [pimutils/todoman#326]
On Arch Linux we're now on click 7.0.
This breaks todoman:

```
Traceback (most recent call last):
  File "/usr/bin/todo", line 11, in <module>
    load_entry_point('todoman==3.4.0', 'console_scripts', 'todo')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
TypeError: cli() got an unexpected keyword argument 'colour'
```

Would be super great to get a bug fix for this one!

**Comment by WhyNotHugo** [comment]
What version of todoman is this? I'm pretty sure this is fixed in the latest version.

**Comment by WhyNotHugo** [comment]
Yeah, see #325.
