### ISSUE TITLE
TypeError: cli() got an unexpected keyword argument 'colour'

### ISSUE THREAD

**Issue by potuz** [pimutils/todoman#331]
After an update here in gentoo

```
# todo
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/todo", line 11, in <module>
    load_entry_point('todoman==3.4.0', 'console_scripts', 'todo')()
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
TypeError: cli() got an unexpected keyword argument 'colour'
```

**Comment by potuz** [comment]
Disregard this please, didn't see the 3.4.1 release, that happened on 3.4.0.
