### ISSUE TITLE
default_list when set in config fails

### ISSUE THREAD

**Issue by ign1s-fatuus** [pimutils/todoman#347]
I am currently having issues setting the default_list variable in my todoman.conf file. I am currently managing 3 different calendars: home, work, and school. As todo currently doesn't have completion for lists I want to set it to one of my currrently managed lists--as it goes into interactive mode I can just change it to the desired list data is entered. 

currently, I have it set as this:

 [main]
  2 # A glob expression which matches all directories relevant.
  3 path = ~/.config/khal/calendars/mySyncedCal/*
  4 cache_path = ~/.local/share/khal/khal.db
  5 date_format = %m-%d-%Y
  6 time_format = %I:%M %p
  7 default_list = Personal
  8 default_due = 48
  9 color = always
 10 humanize = true
 11 default_list = work

When running todo, by itself or with modifiers it returns the following:

 Traceback (most recent call last):
  File "/usr/bin/todo", line 5, in <module>
    cli()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
  File "/usr/lib/python3.7/site-packages/todoman/cli.py", line 273, in cli
    ctx.config = load_config(config)
  File "/usr/lib/python3.7/site-packages/todoman/configuration.py", line 78, in load_config
    config = ConfigObj(path, configspec=specpath, file_error=True)
  File "/usr/lib/python3.7/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python3.7/site-packages/configobj.py", line 1318, in _load
    raise error
configobj.DuplicateError: Duplicate keyword name at line 11.

**Comment by WhyNotHugo** [comment]
You have `default_list` twice: on line 7 and 11. Delete either of those.

**Comment by ign1s-fatuus** [comment]
Good catch. Now I'm all sorts of embarrassed. Thanks for the quick response.

**Comment by WhyNotHugo** [comment]
No prob, it happens.
