### ISSUE TITLE
`cache_path` seems broken

### ISSUE THREAD

**Issue by 73** [pimutils/todoman#350]
Hi there. 

I installed todoman 3.5.0:
```
todoman --version
todoman, version 3.5.0
```

I used the example config file (which works):
```
[main]
# A glob expression which matches all directories relevant.
path = ~/.tasks/*
date_format = %Y-%m-%d
time_format = %H:%M
default_list = Personal
default_due = 48
```
when I set `cache_path = ~/.cache` (which should be the [default](https://todoman.readthedocs.io/en/stable/configure.html)) I run in an SQLite error:

```
Traceback (most recent call last):
  File "/usr/bin/todoman", line 11, in <module>
    load_entry_point('todoman==3.5.0', 'console_scripts', 'todoman')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1109, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
  File "/usr/lib/python3/dist-packages/todoman/cli.py", line 298, in cli
    ctx.db = Database(paths, ctx.config['main']['cache_path'])
  File "/usr/lib/python3/dist-packages/todoman/model.py", line 916, in __init__
    self.cache = Cache(cache_path)
  File "/usr/lib/python3/dist-packages/todoman/model.py", line 404, in __init__
    self._conn = sqlite3.connect(self.cache_path)
sqlite3.OperationalError: unable to open database file
```

**Comment by WhyNotHugo** [comment]
`cache_path` should be the full path to the cache file, not to the directory containing it.

`.cache` is a directory in your case, so it can't be opened as a file. You probably want to specify `~/.cache/todoman.sqlite`.

Note that the default is very close to this anyway.

**Comment by 73** [comment]
Hi,

thanks for clarification. I did not get that from the manual. I guess I would have expected:
> If the value is not specified, the database will be place in the `XDG_CACHE_HOME` directory, generally, `~/.cache`.
> **type**:  cache_path
> **default:** 

to say something like: 
> If the value is not specified, the database will be placed in the `XDG_CACHE_HOME` directory, generally, `~/.cache/todoman.sqlite`.
> **type**:  cache_path
> **default:** $XDG_CACHE_HOME/todoman.sqlite

So it is more clear that a file is to be named. 
Cherrs, and thanks for `todoman`.
