### ISSUE TITLE
fails to start with LANG=eo

### ISSUE THREAD

**Issue by vpzomtrrfrt** [pimutils/todoman#372]
Running `todo` no longer works, it throws on startup:
```
Traceback (most recent call last):
  File "/usr/bin/todo", line 11, in <module>
    load_entry_point('todoman==3.7.0', 'console_scripts', 'todo')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/todoman/cli.py", line 14, in <module>
    from todoman.interactive import TodoEditor
  File "/usr/lib/python3.8/site-packages/todoman/interactive.py", line 1, in <module>
    import urwid
  File "/usr/lib/python3.8/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/usr/lib/python3.8/site-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/usr/lib/python3.8/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/usr/lib/python3.8/site-packages/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

I'm guessing this is related to my locale setting, since it works fine if I override LANG to en_US.UTF-8

**Comment by WhyNotHugo** [comment]
What about `LANG=eo.UTF-8`?

**Comment by vpzomtrrfrt** [comment]
That seems to work, though I'm not sure what else that affects and I've never encountered any issues like this with other programs

**Comment by WhyNotHugo** [comment]
To be honest, I don't know the finer details, only the bits that have been relevant to my usage/development.

Generally, UTF-8 is a good thing; the default is ASCII, which can only encode english characters, while UTF-8 can do the whole unicode spectrum.

Since UTF-8 _extends_ ASCII, nothing should break. I can't honestly thing of something that would, but I encourage you to try switching to that and give it a try.

Unless something breaks using it, I don't really care to research supporting non-UTF-8.

Specifically, we load the `locale` Python module to do all the date/day formatting, and the locale module is the one that only works with `UTF-8`. Python uses UTF-8 by default, and there usually needs to be a good reason to change that.

**Comment by WhyNotHugo** [comment]
Gonna close this, but do reopen if you encounter further issues using UTF-8.

**Comment by vpzomtrrfrt** [comment]
Changing to eo.UTF-8 causes dmenu to crash with `warning: no locale support`

I assumed that not specifying a charset would imply using UTF-8, since that's the way it's configured in glibc, but maybe that's separate from python things

**Comment by vpzomtrrfrt** [comment]
Hmm, yeah, python seems to be interpreting this as ISO8859-3:
```
>>> locale.getlocale()
('eo_XX', 'ISO8859-3')
```
