### ISSUE TITLE
humantime triggers a backtrace

### ISSUE THREAD

**Issue by mathstuf** [pimutils/todoman#383]
Commenting out `humanize = True` in my configuration avoids this. pip-installed 3.7.0.

```
Traceback (most recent call last):
  File "/home/boeckb/.local/bin/todo", line 8, in <module>
    sys.exit(cli())
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/cli.py", line 314, in cli
    ctx.config['main']['default_command'],
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/cli.py", line 324, in invoke_command
    click_ctx.invoke(cli.commands[command], args)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/cli.py", line 645, in list
    click.echo(ctx.formatter.compact_multiple(todos))
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/formatters.py", line 68, in compact_multiple
    due = self.format_datetime(todo.due)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/formatters.py", line 219, in format_datetime
    rv = humanize.naturaltime(self.now - dt)
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
```

**Comment by WhyNotHugo** [comment]
Seems to be happening for todos which have a `date` time (rather than `datetime`) as a `DTSTART`.

**Comment by mathstuf** [comment]
Seems to be more than just a display problem with plain dates (tail end of backtrace here):

```
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/cli.py", line 457, in done
    todo.complete()
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/model.py", line 242, in complete
    related = self._create_next_instance()
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/model.py", line 224, in _create_next_instance
    copy.start = self._apply_recurrence_to_dt(self.start)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/todoman/model.py", line 219, in _apply_recurrence_to_dt
    return recurrence.after(dt)
  File "/home/boeckb/misc/root/todoman/lib/python3.7/site-packages/dateutil/rrule.py", line 224, in after
    if i > dt:
TypeError: can't compare datetime.datetime to datetime.date
```
