### ISSUE TITLE
`todo -h` fails with error

### ISSUE THREAD

**Issue by ryzokuken** [pimutils/todoman#401]
When I try to run `todo -h`, it fails with the following error

```
Traceback (most recent call last):
  File "/usr/bin/todo", line 11, in <module>
    load_entry_point('todoman==3.7.0', 'console_scripts', 'todo')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
  File "/usr/lib/python3.8/site-packages/todoman/cli.py", line 312, in cli
    invoke_command(
  File "/usr/lib/python3.8/site-packages/todoman/cli.py", line 324, in invoke_command
    click_ctx.invoke(cli.commands[command], args)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
  File "/usr/lib/python3.8/site-packages/todoman/cli.py", line 645, in list
    click.echo(ctx.formatter.compact_multiple(todos))
  File "/usr/lib/python3.8/site-packages/todoman/formatters.py", line 68, in compact_multiple
    due = self.format_datetime(todo.due)
  File "/usr/lib/python3.8/site-packages/todoman/formatters.py", line 219, in format_datetime
    rv = humanize.naturaltime(self.now - dt)
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
```

**Comment by WhyNotHugo** [comment]
This has been fixed in master already.

I'm releasing v3.8.0 today which includes this fix.

**Comment by ryzokuken** [comment]
Thanks @WhyNotHugo.
