### ISSUE TITLE
Error when completing a recurrent task whose dates are dates without times

### ISSUE THREAD

**Issue by Hawk777** [pimutils/todoman#405]
Create a task with only dates, not datetimes. Edit the task manually to give it an `RRULE:FREQ=MONTHLY` (since you can’t do that in Todoman, though it supports recurrences created outside itself). Now run `todo done 1234`, where `1234` is the ID of the task.

Expected result: the dates are stepped forward by one month.

Actual result, in 3.7.0:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/todo", line 11, in <module>
    load_entry_point('todoman==3.7.0', 'console_scripts', 'todo')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/todoman/cli.py", line 34, in wrapper
    return f(*a, **kw)
  File "/usr/lib/python3.7/site-packages/todoman/cli.py", line 457, in done
    todo.complete()
  File "/usr/lib/python3.7/site-packages/todoman/model.py", line 242, in complete
    related = self._create_next_instance()
  File "/usr/lib/python3.7/site-packages/todoman/model.py", line 223, in _create_next_instance
    copy.due = self._apply_recurrence_to_dt(self.due)
  File "/usr/lib/python3.7/site-packages/todoman/model.py", line 219, in _apply_recurrence_to_dt
    return recurrence.after(dt)
  File "/usr/lib/python3.7/site-packages/dateutil/rrule.py", line 224, in after
    if i > dt:
TypeError: can't compare datetime.datetime to datetime.date
```

**Comment by Hawk777** [comment]
Apologies for the spam; I didn’t see that 3.8.0 was out. Fixed there.
