### ISSUE TITLE
python-click update to v8 breaks todoman

### ISSUE THREAD

**Issue by aleprovencio** [pimutils/todoman#432]
Hello,
I just got this `python-click`'s update on my Arch install, so downgrading it  to `7.1.2` is enough for now.

**Comment by deafmute1** [comment]
Getting the same issue; if you're interested in the traceback here it is: 
```Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.0 (/usr/lib/python3.9/site-packages), Requirement.parse('click<8.0,>=7.1'), {'todoman'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/todo", line 33, in <module>
    sys.exit(load_entry_point('todoman==3.9.0', 'console_scripts', 'todo')())
  File "/usr/bin/todo", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/todoman/cli.py", line 14, in <module>
    from todoman import formatters
  File "/usr/lib/python3.9/site-packages/todoman/formatters.py", line 6, in <module>
    import humanize
  File "/usr/lib/python3.9/site-packages/humanize/__init__.py", line 2, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'click<8.0,>=7.1' distribution was not found and is required by todoman```
