### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by damionx7** [pimutils/todoman#441]
I updated to todoman 4. and i get this error

```
Traceback (most recent call last):
  File "/home/dev/.pyenv/versions/todoman4-391/bin/todo", line 8, in <module>
    sys.exit(cli())
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/todoman/cli.py", line 38, in wrapper
    return f(*a, **kw)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/todoman/cli.py", line 266, in cli
    ctx.config = load_config(config)
  File "/home/dev/.pyenv/versions/3.9.1/envs/todoman4-391/lib/python3.9/site-packages/todoman/configuration.py", line 228, in load_config
    config_source = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 562, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

config file 

```
# A glob expression which matches all directories relevant.
cache_path = "/var/vmail/.todoman/cache.sqlite3"
path = "/var/vmail/vdirsyncer/calendars/*"
date_format = "%Y-%m-%d"
time_format = "%H:%M"
default_due = 48
default_list = "Inbox"
```

How to solve this ?

**Comment by damionx7** [comment]
Changed config to config.py
