### ISSUE TITLE
Use "tomorrow" and "today" when formatting date

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#82]
When a todo expires today, or tomorrow, show "today" or "tomorrow" respectively instead of the actual date.

**Comment by rimshaakhan** [comment]
Hi, I am new and would like to work on this one.

I am unable to understand the regarding directory structure, can you please help me with the it?

**Comment by hobarrera** [comment]
Hi, thanks for you interest in todoman!

Sorry but no, that's not the actual place change it. The value returned here is used in a few other places that would break:
* Printing with the [`--porcelain`](http://todoman.readthedocs.io/en/stable/usage.html#integrations) flag, which uses a different time format.
* Comparing the date of two `todo`s. (comparing strings like `"today"`,  `"yesterday"` and `2017-03-20` doesn't give the expected results).

As a general rule, the `Todo` class returns data in machine-friendly types (eg: `datetime`, etc) and will be sent back and forth.  
The [`TodoFormatter`](https://github.com/pimutils/todoman/blob/dd8358ebe0c8b165efff1c169f1019598929fc32/todoman/ui.py#L196) class converts `Todo`s into something friendly to humans/users and is what you're looking for. Specifically, the [`format_date`](https://github.com/pimutils/todoman/blob/dd8358ebe0c8b165efff1c169f1019598929fc32/todoman/ui.py#L253-L258) function does this bit (this one *does* return a string).

**Comment by rimshaakhan** [comment]
Oh! I get it now and am likely to send a PR by "tomorrow" :)

**Comment by hobarrera** [comment]
Thanks! Let me know if you have any questions, though in out of town right now and replies might be a little sparse.

**Comment by rimshaakhan** [comment]
Hi @hobarrera 

I am having some trouble with todoman:

I have installed all the required packages, configuration file is in place, but everytime I type ``todo``: A error throws up:
```
Traceback (most recent call last):
  File "/home/im_ishan/Desktop/todoman/todoman_env/bin/todo", line 11, in <module>
    sys.exit(cli())
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/todoman/cli.py", line 117, in cli
    ctx.obj['db'] = Database(paths, cache_path)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/todoman/model.py", line 696, in __init__
    self.cache = Cache(cache_path)
  File "/home/im_ishan/Desktop/todoman/todoman_env/lib/python3.5/site-packages/todoman/model.py", line 366, in __init__
    self.conn = sqlite3.connect(self.cache_path)
sqlite3.OperationalError: unable to open database file
```
Do I need to create the sqlite database manually or am I doing something wrong?

**Comment by untitaker** [comment]
Hello @rimshaakhan, that really shouldn't happen. Could you post the output of `echo $XDG_CACHE_DIR` on your console and also post your configuration file?

**Comment by untitaker** [comment]
Ah I see, you are using the released version of todoman. We really should make a new release, but for development I recommend cloning the todoman repository, `cd`-ing to it, then running this inside of your virtualenv:

    pip install -e .

If you change the code in the git repository, you can see the changes immediately without having to reinstall todoman.

**Comment by rimshaakhan** [comment]
Oh Yeah! That worked

Thanks @untitaker

**Comment by untitaker** [comment]
I use exact datetimes in my due dates (and a custom format string in my config), so introducing this will break my workflow because it will obscure the exact time if my event is happening today or tomorrow. See https://github.com/pimutils/todoman/issues/109
